"""
Handlers for the "extra" exercise types: sentence scramble, fill-in-the-blank,
vocabulary match, translation, and reading-with-summary.

Scored exercise types (scramble, fill-in-the-blank, vocabulary) share a
common completion helper that saves progress and shows a result message.
Open-ended types (translation, summary) use FSM states to capture the
user's free-text reply and don't record a numeric score.
"""

import logging
import random
from typing import List

from aiogram import F, Router
from aiogram.fsm.context import FSMContext
from aiogram.types import CallbackQuery, InlineKeyboardButton, Message
from aiogram.utils.keyboard import InlineKeyboardBuilder

from bot import bot, db
from keyboards import get_back_to_main_keyboard
from states import ExerciseState

router = Router()
logger = logging.getLogger(__name__)


# ----------------------------------------------------------------------
# Shared helpers
# ----------------------------------------------------------------------

async def handle_exercise_completion(
    callback: CallbackQuery, state: FSMContext, exercise_id: int
) -> None:
    """
    Finalize a scored extra exercise.

    Reads the score/total that the calling handler stashed in FSM data
    (`current_score`, `current_total`), saves it to the database, shows a
    success message, and clears the FSM state.
    """
    try:
        data = await state.get_data()
        score = data.get("current_score", 0)
        total = data.get("current_total", 1)

        await db.save_user_progress(callback.from_user.id, exercise_id, score, total)

        await callback.message.answer(
            f"🎉 تمرین تمام شد! نتیجه: {score} از {total}",
            reply_markup=get_back_to_main_keyboard(),
        )
    except Exception as e:
        logger.error(f"Error completing exercise {exercise_id}: {e}")
    finally:
        await state.clear()


def _build_feedback_keyboard(
    options: List[str], chosen_index: int, correct_index: int
) -> InlineKeyboardBuilder:
    """
    Build a read-only feedback keyboard marking the chosen and correct
    options with ✅/❌, with 'noop' callback data for every button.
    """
    builder = InlineKeyboardBuilder()
    for idx, option in enumerate(options):
        is_chosen = idx == chosen_index
        is_correct_option = idx == correct_index
        if is_chosen and is_correct_option:
            label = f"✅ {option}"
        elif is_chosen and not is_correct_option:
            label = f"❌ {option}"
        elif is_correct_option:
            label = f"✅ {option}"
        else:
            label = option
        builder.row(InlineKeyboardButton(text=label, callback_data="noop"))
    return builder


@router.callback_query(F.data == "noop")
async def handle_noop(callback: CallbackQuery) -> None:
    """Swallow taps on already-answered feedback buttons."""
    await callback.answer()


# ----------------------------------------------------------------------
# Scramble (sentence ordering)
# ----------------------------------------------------------------------

def _generate_scramble_options(
    words: List[str], correct_sentence: str, num_options: int = 3
) -> List[str]:
    """
    Build a shuffled list of sentence options, one of which is the correct
    ordering of `words`. Distractors are generated by re-shuffling the same
    words; if not enough distinct distractors can be produced, the list may
    end up shorter than `num_options`.
    """
    options = {correct_sentence}
    attempts = 0
    while len(options) < num_options and attempts < 20:
        shuffled = words[:]
        random.shuffle(shuffled)
        candidate = " ".join(shuffled)
        if candidate.strip():
            options.add(candidate)
        attempts += 1

    options_list = list(options)
    random.shuffle(options_list)
    return options_list


@router.callback_query(F.data.startswith("start_scramble:"))
async def handle_start_scramble(callback: CallbackQuery, state: FSMContext) -> None:
    """Present a scrambled sentence and multiple-choice reordering options."""
    try:
        exercise_id = int(callback.data.split(":")[1])
        exercise = await db.get_exercise(exercise_id)

        if not exercise:
            await callback.answer("⚠️ تمرین یافت نشد.", show_alert=True)
            return

        content = exercise.get("content")
        if (
            not isinstance(content, dict)
            or "words" not in content
            or "correct" not in content
        ):
            await callback.message.answer(
                "⚠️ این تمرین به درستی تنظیم نشده است.",
                reply_markup=get_back_to_main_keyboard(),
            )
            await callback.answer()
            return

        words = content["words"]
        correct_sentence = content["correct"]

        options = _generate_scramble_options(words, correct_sentence)
        correct_index = options.index(correct_sentence)

        # Persist the generated options so the answer handler validates
        # against the exact same choices the user was shown.
        await state.update_data(
            scramble_exercise_id=exercise_id,
            scramble_options=options,
            scramble_correct_index=correct_index,
        )

        builder = InlineKeyboardBuilder()
        for idx, option in enumerate(options):
            builder.row(
                InlineKeyboardButton(
                    text=option, callback_data=f"scramble_answer:{exercise_id}:{idx}"
                )
            )

        await callback.message.answer(
            "🔀 این کلمات را مرتب کن:\n\n" + " / ".join(words),
            reply_markup=builder.as_markup(),
        )
        await callback.answer()
    except Exception as e:
        logger.error(f"Error starting scramble exercise '{callback.data}': {e}")
        await callback.answer("⚠️ خطایی رخ داد.", show_alert=True)


@router.callback_query(F.data.startswith("scramble_answer:"))
async def handle_scramble_answer(callback: CallbackQuery, state: FSMContext) -> None:
    """Grade the chosen sentence ordering and finish the exercise."""
    try:
        _, exercise_id_raw, opt_index_raw = callback.data.split(":")
        exercise_id = int(exercise_id_raw)
        opt_index = int(opt_index_raw)

        data = await state.get_data()
        if data.get("scramble_exercise_id") != exercise_id:
            await callback.answer(
                "⚠️ این تمرین دیگر معتبر نیست. دوباره شروع کن.", show_alert=True
            )
            return

        options = data.get("scramble_options", [])
        correct_index = data.get("scramble_correct_index")
        is_correct = opt_index == correct_index

        builder = _build_feedback_keyboard(options, opt_index, correct_index)
        try:
            await callback.message.edit_reply_markup(reply_markup=builder.as_markup())
        except Exception:
            pass

        await state.update_data(current_score=1 if is_correct else 0, current_total=1)
        await handle_exercise_completion(callback, state, exercise_id)
        await callback.answer()
    except Exception as e:
        logger.error(f"Error grading scramble answer '{callback.data}': {e}")
        await callback.answer("⚠️ خطایی رخ داد.", show_alert=True)


# ----------------------------------------------------------------------
# Fill in the blank
# ----------------------------------------------------------------------

@router.callback_query(F.data.startswith("start_fillblank:"))
async def handle_start_fillblank(callback: CallbackQuery, state: FSMContext) -> None:
    """Present a fill-in-the-blank sentence with multiple-choice options."""
    try:
        exercise_id = int(callback.data.split(":")[1])
        exercise = await db.get_exercise(exercise_id)

        if not exercise:
            await callback.answer("⚠️ تمرین یافت نشد.", show_alert=True)
            return

        content = exercise.get("content")
        if (
            not isinstance(content, dict)
            or "sentence" not in content
            or "options" not in content
        ):
            await callback.message.answer(
                "⚠️ این تمرین به درستی تنظیم نشده است.",
                reply_markup=get_back_to_main_keyboard(),
            )
            await callback.answer()
            return

        builder = InlineKeyboardBuilder()
        for idx, option in enumerate(content["options"]):
            builder.row(
                InlineKeyboardButton(
                    text=option, callback_data=f"fillblank_answer:{exercise_id}:{idx}"
                )
            )

        await callback.message.answer(
            f"📝 جای خالی را پر کن:\n\n{content['sentence']}",
            reply_markup=builder.as_markup(),
        )
        await callback.answer()
    except Exception as e:
        logger.error(f"Error starting fill-blank exercise '{callback.data}': {e}")
        await callback.answer("⚠️ خطایی رخ داد.", show_alert=True)


@router.callback_query(F.data.startswith("fillblank_answer:"))
async def handle_fillblank_answer(callback: CallbackQuery, state: FSMContext) -> None:
    """Grade the chosen fill-in-the-blank option and finish the exercise."""
    try:
        _, exercise_id_raw, opt_index_raw = callback.data.split(":")
        exercise_id = int(exercise_id_raw)
        opt_index = int(opt_index_raw)

        exercise = await db.get_exercise(exercise_id)
        content = exercise.get("content") if exercise else None
        if not isinstance(content, dict):
            await callback.answer("⚠️ تمرین یافت نشد.", show_alert=True)
            return

        options = content.get("options", [])
        correct_index = content.get("correct")
        is_correct = opt_index == correct_index

        builder = _build_feedback_keyboard(options, opt_index, correct_index)
        try:
            await callback.message.edit_reply_markup(reply_markup=builder.as_markup())
        except Exception:
            pass

        if not is_correct:
            note = content.get("note")
            note_text = f"\n\n💡 نکته: {note}" if note else ""
            await callback.message.answer(f"❌ اشتباه بود.{note_text}")

        await state.update_data(current_score=1 if is_correct else 0, current_total=1)
        await handle_exercise_completion(callback, state, exercise_id)
        await callback.answer()
    except Exception as e:
        logger.error(f"Error grading fill-blank answer '{callback.data}': {e}")
        await callback.answer("⚠️ خطایی رخ داد.", show_alert=True)


# ----------------------------------------------------------------------
# Vocabulary match
# ----------------------------------------------------------------------

@router.callback_query(F.data.startswith("start_vocab:"))
async def handle_start_vocab(callback: CallbackQuery, state: FSMContext) -> None:
    """Present a vocabulary word with multiple-choice meaning options."""
    try:
        exercise_id = int(callback.data.split(":")[1])
        exercise = await db.get_exercise(exercise_id)

        if not exercise:
            await callback.answer("⚠️ تمرین یافت نشد.", show_alert=True)
            return

        content = exercise.get("content")
        if (
            not isinstance(content, dict)
            or "word" not in content
            or "options" not in content
        ):
            await callback.message.answer(
                "⚠️ این تمرین به درستی تنظیم نشده است.",
                reply_markup=get_back_to_main_keyboard(),
            )
            await callback.answer()
            return

        builder = InlineKeyboardBuilder()
        for idx, option in enumerate(content["options"]):
            builder.row(
                InlineKeyboardButton(
                    text=option, callback_data=f"vocab_answer:{exercise_id}:{idx}"
                )
            )

        await callback.message.answer(
            f"📖 معنی این کلمه چیست؟\n\n<b>{content['word']}</b>",
            reply_markup=builder.as_markup(),
        )
        await callback.answer()
    except Exception as e:
        logger.error(f"Error starting vocab exercise '{callback.data}': {e}")
        await callback.answer("⚠️ خطایی رخ داد.", show_alert=True)


@router.callback_query(F.data.startswith("vocab_answer:"))
async def handle_vocab_answer(callback: CallbackQuery, state: FSMContext) -> None:
    """Grade the chosen vocabulary meaning and finish the exercise."""
    try:
        _, exercise_id_raw, opt_index_raw = callback.data.split(":")
        exercise_id = int(exercise_id_raw)
        opt_index = int(opt_index_raw)

        exercise = await db.get_exercise(exercise_id)
        content = exercise.get("content") if exercise else None
        if not isinstance(content, dict):
            await callback.answer("⚠️ تمرین یافت نشد.", show_alert=True)
            return

        options = content.get("options", [])
        correct_index = content.get("correct")
        is_correct = opt_index == correct_index

        builder = _build_feedback_keyboard(options, opt_index, correct_index)
        try:
            await callback.message.edit_reply_markup(reply_markup=builder.as_markup())
        except Exception:
            pass

        await state.update_data(current_score=1 if is_correct else 0, current_total=1)
        await handle_exercise_completion(callback, state, exercise_id)
        await callback.answer()
    except Exception as e:
        logger.error(f"Error grading vocab answer '{callback.data}': {e}")
        await callback.answer("⚠️ خطایی رخ داد.", show_alert=True)


# ----------------------------------------------------------------------
# Translation (open-ended, FSM-based)
# ----------------------------------------------------------------------

@router.callback_query(F.data.startswith("start_translation:"))
async def handle_start_translation(callback: CallbackQuery, state: FSMContext) -> None:
    """Prompt the user to translate a sentence and await their free-text reply."""
    try:
        exercise_id = int(callback.data.split(":")[1])
        exercise = await db.get_exercise(exercise_id)

        if not exercise:
            await callback.answer("⚠️ تمرین یافت نشد.", show_alert=True)
            return

        content = exercise.get("content")
        if not isinstance(content, dict) or "source" not in content:
            await callback.message.answer(
                "⚠️ این تمرین به درستی تنظیم نشده است.",
                reply_markup=get_back_to_main_keyboard(),
            )
            await callback.answer()
            return

        await state.set_state(ExerciseState.waiting_for_translation)
        await state.update_data(translation_exercise_id=exercise_id)

        await callback.message.answer(
            f"🔄 این جمله را ترجمه کن:\n\n<b>{content['source']}</b>\n\n"
            "✍️ ترجمه خودت را بفرست:"
        )
        await callback.answer()
    except Exception as e:
        logger.error(f"Error starting translation exercise '{callback.data}': {e}")
        await callback.answer("⚠️ خطایی رخ داد.", show_alert=True)


@router.message(ExerciseState.waiting_for_translation, F.text)
async def handle_translation_reply(message: Message, state: FSMContext) -> None:
    """Receive the user's translation attempt and show the suggested one."""
    try:
        data = await state.get_data()
        exercise_id = data.get("translation_exercise_id")
        exercise = await db.get_exercise(exercise_id) if exercise_id else None
        content = exercise.get("content") if exercise else None

        if not isinstance(content, dict):
            await message.answer(
                "⚠️ متأسفانه اطلاعات این تمرین یافت نشد.",
                reply_markup=get_back_to_main_keyboard(),
            )
            await state.clear()
            return

        target = content.get("target", "")
        note = content.get("note", "")

        note_text = f"\n\n💡 نکته: {note}" if note else ""
        await message.answer(
            "✅ ترجمه شما ثبت شد.\n\n"
            f"📝 ترجمه پیشنهادی:\n<b>{target}</b>{note_text}",
            reply_markup=get_back_to_main_keyboard(),
        )
    except Exception as e:
        logger.error(f"Error handling translation reply: {e}")
    finally:
        await state.clear()


# ----------------------------------------------------------------------
# Reading with summary (open-ended, FSM-based)
# ----------------------------------------------------------------------

@router.callback_query(F.data.startswith("start_reading:"))
async def handle_start_reading(callback: CallbackQuery, state: FSMContext) -> None:
    """Present a reading passage with options to answer questions or summarize."""
    try:
        exercise_id = int(callback.data.split(":")[1])
        exercise = await db.get_exercise(exercise_id)

        if not exercise:
            await callback.answer("⚠️ تمرین یافت نشد.", show_alert=True)
            return

        if exercise.get("audio_file_id"):
            await bot.send_voice(
                chat_id=callback.message.chat.id, voice=exercise["audio_file_id"]
            )

        transcript = (
            exercise.get("transcript") or "⚠️ متنی برای این تمرین ثبت نشده است."
        )
        await callback.message.answer(transcript)

        builder = InlineKeyboardBuilder()
        questions = exercise.get("questions")
        if isinstance(questions, list) and questions:
            builder.row(
                InlineKeyboardButton(
                    text="📝 شروع سوالات",
                    callback_data=f"begin_questions:{exercise_id}",
                )
            )
        builder.row(
            InlineKeyboardButton(
                text="✍️ ارسال خلاصه من",
                callback_data=f"request_summary:{exercise_id}",
            )
        )

        await callback.message.answer(
            "چه کاری می‌خواهی انجام بدهی؟", reply_markup=builder.as_markup()
        )
        await callback.answer()
    except Exception as e:
        logger.error(f"Error starting reading exercise '{callback.data}': {e}")
        await callback.answer("⚠️ خطایی رخ داد.", show_alert=True)


@router.callback_query(F.data.startswith("request_summary:"))
async def handle_request_summary(callback: CallbackQuery, state: FSMContext) -> None:
    """Ask the user to write a short summary of the reading passage."""
    try:
        exercise_id = int(callback.data.split(":")[1])

        await state.set_state(ExerciseState.waiting_for_summary)
        await state.update_data(summary_exercise_id=exercise_id)

        await callback.message.answer("✍️ خلاصه این متن را در ۲-۳ جمله بنویس و بفرست:")
        await callback.answer()
    except Exception as e:
        logger.error(f"Error requesting summary '{callback.data}': {e}")
        await callback.answer("⚠️ خطایی رخ داد.", show_alert=True)


@router.message(ExerciseState.waiting_for_summary, F.text)
async def handle_summary_reply(message: Message, state: FSMContext) -> None:
    """Receive the user's summary and show a suggested sample summary."""
    try:
        data = await state.get_data()
        exercise_id = data.get("summary_exercise_id")
        exercise = await db.get_exercise(exercise_id) if exercise_id else None

        if not exercise:
            await message.answer(
                "⚠️ متأسفانه اطلاعات این تمرین یافت نشد.",
                reply_markup=get_back_to_main_keyboard(),
            )
            await state.clear()
            return

        # `grammar_notes` doubles as the sample-summary field for reading
        # exercises, to avoid adding a new schema column for this part.
        sample_summary = exercise.get("grammar_notes")
        sample_text = (
            f"\n\n📝 نمونه خلاصه پیشنهادی:\n{sample_summary}"
            if sample_summary
            else ""
        )

        builder = InlineKeyboardBuilder()
        questions = exercise.get("questions")
        if isinstance(questions, list) and questions:
            builder.row(
                InlineKeyboardButton(
                    text="📝 شروع سوالات",
                    callback_data=f"begin_questions:{exercise_id}",
                )
            )
        else:
            builder.row(
                InlineKeyboardButton(text="🏠 منوی اصلی", callback_data="back:main")
            )

        await message.answer(
            f"✅ خلاصه شما ثبت شد!{sample_text}", reply_markup=builder.as_markup()
        )
    except Exception as e:
        logger.error(f"Error handling summary reply: {e}")
    finally:
        await state.clear()
